### ISSUE TITLE
Learn Android

### ISSUE THREAD

**Issue by khammami** [Enet-Com-23/pfa-eval-android-project#4]
[TPs Link](https://codelabs-enetcom.khammami.tn/enetcomtppem/)
- [x] [TP 1.1](https://classroom.github.com/a/AdwNtz_J)
- [x] [TP 2.1](https://classroom.github.com/a/RxSrDaPN)
- [x] [TP 2.2](https://classroom.github.com/a/gOxzqYaX)
- [x] [TP 2.3](https://classroom.github.com/a/g2hDMtoo)

**Comment by khammami** [comment]
@achrafbenabdalla I generated new links for you.

Close #14 , Close #15

**Comment by achrafbenabdalla** [comment]
@khammami thank you , but i didn't recive anthing in mail from github classrom like the last time ,and pleas check my work within tp1.1 to know that idid well or not

**Comment by khammami** [comment]
@achrafbenabdalla GitHub Classroom doesn't send notifications/emails for assignments. The teacher should share them with his students.
Yes, I'll check them tonight.
